version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: reqwest
    versions:
    - 0.11.2
  - dependency-name: serde
    versions:
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.64
  - dependency-name: bincode
    versions:
    - 1.3.2
  - dependency-name: url
    versions:
    - 2.2.1
  - dependency-name: log
    versions:
    - 0.4.13
    - 0.4.14
  - dependency-name: termion
    versions:
    - 1.5.6
  - dependency-name: regex
    versions:
    - 1.4.3
  - dependency-name: byteorder
    versions:
    - 1.4.2
  - dependency-name: yaml-rust
    versions:
    - 0.4.5
  - dependency-name: dtoa
    versions:
    - 0.4.7
  rebase-strategy: disabled
